# PROJETO - <strong>Ciência de Dados</strong> - Disciplina <i>Estatística</i>
## <i>Análise estatística do acervo do MoMA</i>
###### por Osmar Domingos

#### fonte dos dados: <a src="https://github.com/MuseumofModernArt/collection">MoMA Collection</a>

<img src="https://www.moma.org/d/p/sa/07-29-24_240518_MoMA%20Family%20Programs_036_large_NT.jpg">

### 1ª Etapa <i>O que existe aqui e o que está faltando?</i>

A fazer (4/4 - 10/4/2026):

<i>
<ol>
    <li>Carregar o dataset do MoMA [✅]</li>
    <li>Mapear colunas disponíveis [❌]</li>
    <li>Limpeza inicial: nulos, tipos, inconsistências [❌]</li>
</ol>
</i>

<hr>

## Carregar datasets do museu

<i>Bibliotecas:</i>

In [1]:
import pandas as pd

<i>Carregamento em dataframes dos arquivos .csv</i>

In [3]:
df_artistas = pd.read_csv("../data/raw/Artists.csv")
df_obras = pd.read_csv("../data/raw/Artworks.csv")

<i>Gerar amostras de 10 casos de cada dataframe, tendo assim uma ideia inicial da estrutura do dataset sem ver apenas os primeiros ou últimos, para  que o olhar sobre este seja mais exploratório</i>

In [4]:
df_artistas.sample(10)

,ConstituentID,DisplayName,ArtistBio,Nationality,Gender,BeginDate,EndDate,Wiki QID,ULAN
3615,4030,Petr Miturich,"Russian, 1887–1956",Russian,male,1887,1956,NaN,NaN
6473,7209,Giotto Stoppino,"Italian, 1926–2011",Italian,male,1926,2011,NaN,NaN
14648,68785,Irving Schott,"American, 1891–1990",American,male,1891,1990,NaN,NaN
10225,28710,Keith Mayerson,"American, born 1966",American,male,1966,0,NaN,NaN
8155,10277,"Beamo Corporation, Cambridge, MA",NaN,NaN,NaN,0,0,NaN,NaN
11144,32686,Tom O'Sullivan,"British, born 1967",British,male,1967,0,NaN,NaN
1853,2092,Lee Gatch,"American, 1902–1968",American,male,1902,1968,Q15487727,500025517.0
15591,137007,Adrian Henri,"British, 1932–2000",British,male,1932,2000,NaN,NaN
13281,44936,Antonio Puente,Venezuelan,Venezuelan,male,0,0,NaN,NaN
951,1069,André Chapon,French,French,male,0,0,NaN,NaN

In [5]:
df_obras.sample(10)

,Title,Artist,ConstituentID,ArtistBio,Nationality,BeginDate,EndDate,Gender,Date,Medium,...,OnView,Circumference (cm),Depth (cm),Diameter (cm),Height (cm),Length (cm),Weight (kg),Width (cm),Seat Height (cm),Duration (sec.)
111220,Poster of the French National Railroad,Album-miscellaneous,101,(Various),(),(0),(0),(),1900-1943,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134736,100 Boots,Eleanor Antin,8183,"(American, born 1935)",(American),(1935),(0),(female),1971-73,Halftone reproduction (postcard),...,NaN,NaN,NaN,NaN,11.400000,NaN,NaN,17.800000,NaN,NaN
50927,Siesta,László Moholy-Nagy,4048,"(American, born Hungary. 1895–1946)",(American),(1895),(1946),(male),1926,Gelatin silver print,...,NaN,NaN,NaN,NaN,23.300000,NaN,NaN,17.200000,NaN,NaN
43628,"Infantry Assault, Stalingrad",Georgi Zelma,7978,"(Russian, born Tashkent, Uzbekistan.1906–1984)",(Russian),(1906),(1984),(male),1943,Gelatin silver print,...,NaN,NaN,NaN,NaN,20.200000,NaN,NaN,27.300000,NaN,NaN
16442,"SUNDAY, proof of 1st color (supplementary suit...",Jean Dubuffet,1633,"(French, 1901–1985)",(French),(1901),(1985),(male),1949-1950,"Lithograph, printed in color",...,NaN,NaN,NaN,NaN,20.200000,NaN,NaN,20.200000,NaN,NaN
79947,"Illinois Institute of Technology, S.R. Crown H...",Ludwig Mies van der Rohe,7166,"(American, born Germany. 1886–1969)",(American),(1886),(1969),(male),1950-56,Pencil on Apex note paper,...,NaN,NaN,NaN,NaN,15.240000,NaN,NaN,21.590000,NaN,NaN
90274,Road to Nowhere,"David Byrne, Stephen R. Johnson","8200, 32196","(American, born 1952) (American)",(American) (American),(1952) (1952),(0) (2015),(male) (male),1985,"Video (color, sound) \r\n",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244.0
120202,"Kempner House, Charlottenburg, Berlin, Germany",Ludwig Mies van der Rohe,7166,"(American, born Germany. 1886–1969)",(American),(1886),(1969),(male),1922,Print,...,NaN,NaN,NaN,NaN,74.295149,NaN,NaN,96.520193,NaN,NaN
536,"Maison de la Publicité Project, Paris, France ...",Oscar Nitzchke,4312,"(American, born Germany. 1900–1991)",(American),(1900),(1991),(male),1936,"Ink, color pencil, gouache, and graphite on sp...",...,NaN,NaN,NaN,NaN,71.120100,NaN,NaN,52.070100,NaN,NaN
34319,"Untitled at 2,783,195",Jonathan Borofsky,682,"(American, born 1942)",(American),(1942),(0),(male),(1982),Ink and gouache on paper,...,NaN,NaN,NaN,NaN,20.100000,NaN,NaN,15.500000,NaN,NaN

* A 'chave estrangeira' que relaciona artistas e obras é <strong>ConstituentID</strong>.

<i>Quantos casos (linhas) e variáveis (colunas) tem nos DF?</i>

In [7]:
print(f"Artistas - Número de casos (linhas): {df_artistas.shape[0]}. Números de variáveis (colunas): {df_artistas.shape[1]}.")

Artistas - Número de casos (linhas): 15859. Números de variáveis (colunas): 9.

In [8]:
print(f"Obras - Número de casos (linhas): {df_obras.shape[0]}. Números de variáveis (colunas): {df_obras.shape[1]}.")

Obras - Número de casos (linhas): 160632. Números de variáveis (colunas): 30.

<i>Quais são as variáveis de cada DF?</i>

In [12]:
df_artistas.columns

Index(['ConstituentID', 'DisplayName', 'ArtistBio', 'Nationality', 'Gender',
       'BeginDate', 'EndDate', 'Wiki QID', 'ULAN'],
      dtype='str')

In [13]:
df_obras.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ImageURL', 'OnView',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='str')