# PROJETO - <strong>Ciência de Dados</strong> - Disciplina <i>Estatística</i>
## <i>Análise estatística do acervo do MoMA</i>
###### por Osmar Domingos

#### fonte dos dados: <a src="https://github.com/MuseumofModernArt/collection">MoMA Collection</a>
###### Data de Coleta: 04/04/2026

<img src="https://www.moma.org/d/p/sa/07-29-24_240518_MoMA%20Family%20Programs_036_large_NT.jpg">

### 1ª Etapa <i>O que existe aqui e o que está faltando?</i>

A fazer (4/4 - 10/4/2026):

<i>
<ol>
    <li>Carregar o dataset do MoMA [✅]</li>
    <li>Mapear colunas disponíveis [❌]</li>
    <li>Limpeza inicial: nulos, tipos, inconsistências [❌]</li>
</ol>
</i>

<hr>

## Carregar datasets do museu

<i>Bibliotecas:</i>

In [83]:
import pandas as pd

<i>Carregamento em dataframes dos arquivos .csv</i>

In [84]:
df_artistas = pd.read_csv("../data/raw/Artists.csv")
df_obras = pd.read_csv("../data/raw/Artworks.csv")

<span  style="background-color: blue; color: white"><i>Gerar amostras de 10 casos de cada dataframe, tendo assim uma ideia inicial da estrutura do dataset sem ver apenas os primeiros ou últimos, para  que o olhar sobre este seja mais exploratório</i></span>

In [85]:
df_artistas.sample(10)

,ConstituentID,DisplayName,ArtistBio,Nationality,Gender,BeginDate,EndDate,Wiki QID,ULAN
7980,9845,"Canon, Inc., Japan","Japanese, established 1947",Japanese,NaN,1947,0,NaN,NaN
11761,35541,Kit Galloway,"American, born 1948",American,male,1948,0,NaN,NaN
5539,6178,Lucien Vlerick,"Belgian, born 1921",Belgian,male,1921,0,NaN,NaN
8051,10061,"Rossi & Arcandi, Vicenza, Italy",NaN,NaN,NaN,0,0,NaN,NaN
592,668,Maria Bonomi,"Brazilian, born 1935",Brazilian,female,1935,0,Q10325755,NaN
13000,42736,Apichatpong Weerasethakul,"Thai, born 1970",Thai,male,1970,0,NaN,NaN
11840,35639,Wang Jianwei,"Chinese, born 1958",Chinese,male,1958,0,NaN,NaN
10547,29718,Javier Peña,NaN,NaN,NaN,0,0,NaN,NaN
4060,4533,Max Pechstein,"German, 1881–1955",German,male,1881,1955,Q162105,500032015.0
12560,39841,caraballo-farman,NaN,NaN,NaN,0,0,NaN,NaN

In [86]:
df_obras.sample(10)

,Title,Artist,ConstituentID,ArtistBio,Nationality,BeginDate,EndDate,Gender,Date,Medium,...,OnView,Circumference (cm),Depth (cm),Diameter (cm),Height (cm),Length (cm),Weight (kg),Width (cm),Seat Height (cm),Duration (sec.)
60955,"Scopes of Blue, Red, Yellow",Benni Efrat,1687,(Israeli),(Israeli),(0),(0),(male),(1974),Portfolio of six screenprints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79789,Untitled,Arturo Herrera,25582,"(Venezuelan, born 1959)",(Venezuelan),(1959),(0),(male),1997–98,Cut-and-pasted printed paper on envelope,...,NaN,NaN,NaN,NaN,29.8451,NaN,NaN,22.860,NaN,NaN
81428,"Aspirin® Tablet, 500 mg.",Bayer Research Laboratories,26954,"(German, founded 1863)",(German),(1863),(0),(),1900,Acetylsalicylic Acid (ASA),...,NaN,NaN,NaN,1.27,0.3175,NaN,NaN,NaN,NaN,NaN
112262,Text panel from the series Fish Story,Allan Sekula,31040,"(American, 1951–2013)",(American),(1951),(2013),(male),1988-95,NaN,...,NaN,NaN,NaN,NaN,101.7000,NaN,NaN,71.100,NaN,NaN
145064,"American Association of Railroads Complex, Chi...",Ludwig Mies van der Rohe,7166,"(American, born Germany. 1886–1969)",(American),(1886),(1969),(male),1948—1956,Pencil on vellum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72481,Cast of Characters,José Luis Cuevas,1325,"(Mexican, 1934–2017)",(Mexican),(1934),(2017),(male),1965,Lithograph,...,NaN,NaN,NaN,NaN,19.5000,NaN,NaN,77.600,NaN,NaN
32546,Untitled from Cuban Sketch Book,Jules Pascin,4514,"(American, born Bulgaria. 1885–1930)",(American),(1885),(1930),(male),(c. 1914-20),Pencil on paper,...,NaN,NaN,NaN,NaN,11.1000,NaN,NaN,13.000,NaN,NaN
24403,CHRIST WALKING THE WATER plate XIV (folio 17) ...,James Ensor,1739,"(Belgian, 1860–1949)",(Belgian),(1860),(1949),(male),1913-1921,NaN,...,NaN,NaN,NaN,NaN,15.3000,NaN,NaN,21.000,NaN,NaN
891,"House, Breganoza, Switzerland (Scale model, 1:36)",Mario Botta,696,"(Swiss, born 1943)",(Swiss),(1943),(0),(male),1984,Wood,...,NaN,NaN,80.3277,NaN,63.5000,NaN,NaN,116.364,NaN,NaN
111164,Poster of the French National Railroad,Album-miscellaneous,101,(Various),(),(0),(0),(),1900-1943,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<span style="background-color: yellow">A 'chave estrangeira' que relaciona artistas e obras é <strong>ConstituentID</strong>.</span>

<span  style="background-color: blue; color: white"><i>Quantos casos (linhas) e variáveis (colunas) tem nos DF?</i></span>

In [87]:
print(f"Artistas - Número de casos (linhas): {df_artistas.shape[0]}. Números de variáveis (colunas): {df_artistas.shape[1]}.")

Artistas - Número de casos (linhas): 15859. Números de variáveis (colunas): 9.

In [88]:
print(f"Obras - Número de casos (linhas): {df_obras.shape[0]}. Números de variáveis (colunas): {df_obras.shape[1]}.")

Obras - Número de casos (linhas): 160632. Números de variáveis (colunas): 30.

<span  style="background-color: blue; color: white"><i>Quais são as variáveis de cada DF?</i></span>

<strong>Artistas:</strong>

In [89]:
df_artistas.columns

Index(['ConstituentID', 'DisplayName', 'ArtistBio', 'Nationality', 'Gender',
       'BeginDate', 'EndDate', 'Wiki QID', 'ULAN'],
      dtype='str')

In [90]:
dict_variaveis_df_artistas = {
    "Variáveis": [],
    "Tipo de dado": [],
    "Descrição": [],
    "Tipo de variável": [],
    "Ações": []
}

for column in df_artistas.columns:
    dict_variaveis_df_artistas["Variáveis"].append(column)
    dict_variaveis_df_artistas["Tipo de dado"].append(type(column).__name__)
    dict_variaveis_df_artistas["Descrição"].append('')
    dict_variaveis_df_artistas["Tipo de variável"].append('')
    dict_variaveis_df_artistas["Ações"].append('')

In [91]:
dict_variaveis_df_artistas

{'Variáveis': ['ConstituentID',
  'DisplayName',
  'ArtistBio',
  'Nationality',
  'Gender',
  'BeginDate',
  'EndDate',
  'Wiki QID',
  'ULAN'],
 'Tipo de dado': ['str',
  'str',
  'str',
  'str',
  'str',
  'str',
  'str',
  'str',
  'str'],
 'Descrição': ['', '', '', '', '', '', '', '', ''],
 'Tipo de variável': ['', '', '', '', '', '', '', '', ''],
 'Ações': ['', '', '', '', '', '', '', '', '']}

In [92]:
df_artistas_variaveis = pd.DataFrame(data=dict_variaveis_df_artistas)

In [93]:
descricoes = [
    "'Chave estrangeira' que relaciona Artistas com Obras",
    "Nome do artista/organização",
    "Nacionalidade e data de nasc. - falecimento",
    "Nacionalidade",
    "Gênero",
    "Ano de nascimento",
    "Ano de falecimento",
    "ID de busca na WikiData",
    "ID da Union List of Artist Names® da Getty Research Institue"
]

tipos_de_variaveis = [
    "numérica discreta",
    "categórica nominal",
    "categórica nominal",
    "categórica nominal",
    "categórica nominal",
    "numérica discreta",
    "numérica discreta",
    "categórica nominal",
    "categórica nominal"
]

acoes = [
    "Converter em int",
    "Nenhuma",
    "Remover: outras colunas dão conta da mesma informação de forma isolada e de mais fácil leitura e manipulação",
    "Alterar NaN para 'Nationality unknown', que já está presente no dataset",
    "Investigar se há outra indicação de gênero além de 'male' ou 'female'",
    "Converter em int para poder fazer operações de idade",
    "Converter em int para poder fazer operações",
    "Converter em URL para acesso rápido 'https://www.wikidata.org/wiki/<Wiki QID>'",
    "Primeiro remover o '.0', que não retorna nada, então converter em URL para acesso rápido 'https://www.getty.edu/vow/ULANFullDisplay?find=<ULAN>&role=&nation=&prev_page=1&subjectid=<ULAN>'"
]

for i in df_artistas_variaveis.index:
    df_artistas_variaveis.at[i, 'Descrição'] = descricoes[i]
    df_artistas_variaveis.at[i, 'Tipo de variável'] = tipos_de_variaveis[i]
    df_artistas_variaveis.at[i, 'Ações'] = acoes[i]

<span style="background-color: yellow">Tabela descritiva do dataframe df_artistas:</span>

In [94]:
with pd.option_context('display.max_colwidth', None):
    display(df_artistas_variaveis)

,Variáveis,Tipo de dado,Descrição,Tipo de variável,Ações
0,ConstituentID,str,'Chave estrangeira' que relaciona Artistas com Obras,numérica discreta,Converter em int
1,DisplayName,str,Nome do artista/organização,categórica nominal,Nenhuma
2,ArtistBio,str,Nacionalidade e data de nasc. - falecimento,categórica nominal,Remover: outras colunas dão conta da mesma informação de forma isolada e de mais fácil leitura e manipulação
3,Nationality,str,Nacionalidade,categórica nominal,"Alterar NaN para 'Nationality unknown', que já está presente no dataset"
4,Gender,str,Gênero,categórica nominal,Investigar se há outra indicação de gênero além de 'male' ou 'female'
5,BeginDate,str,Ano de nascimento,numérica discreta,Converter em int para poder fazer operações de idade
6,EndDate,str,Ano de falecimento,numérica discreta,Converter em int para poder fazer operações
7,Wiki QID,str,ID de busca na WikiData,categórica nominal,Converter em URL para acesso rápido 'https://www.wikidata.org/wiki/<Wiki QID>'
8,ULAN,str,ID da Union List of Artist Names® da Getty Research Institue,categórica nominal,"Primeiro remover o '.0', que não retorna nada, então converter em URL para acesso rápido 'https://www.getty.edu/vow/ULANFullDisplay?find=<ULAN>&role=&nation=&prev_page=1&subjectid=<ULAN>'"

<strong>Obras de arte:</strong>

In [95]:
df_obras.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ImageURL', 'OnView',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='str')